sensor:
  - platform: mqtt
    name: Electricity Meter Day
    unique_id: electricity_meter_day
    state_class: total_increasing
    device_class: energy
    state_topic: "meter_electricity/total_rate_1"
    unit_of_measurement: kWh
    value_template: "{{ value | float * 0.001 }}"
  - platform: mqtt
    name: Electricity Meter Night
    unique_id: electricity_meter_night
    state_class: total_increasing
    device_class: energy
    state_topic: "meter_electricity/total_rate_2"
    unit_of_measurement: kWh
    value_template: "{{ value | float * 0.001 }}"
  - platform: mqtt
    name: Electricity Meter Total
    unique_id: electricity_meter_total
    state_class: total_increasing
    device_class: energy
    state_topic: "meter_electricity/total"
    unit_of_measurement: kWh
    value_template: "{{ value | float * 0.001 }}"
  - platform: mqtt
    name: Electricity Meter Battery Voltage
    unique_id: electricity_meter_battery_voltage
    device_class: voltage
    state_topic: "meter_electricity/battery"
    unit_of_measurement: V
    value_template: "{{ value | float }}"
  - platform: mqtt
    name: Electricity Meter Battery
    unique_id: electricity_meter_battery
    device_class: battery
    unit_of_measurement: "%"
    state_topic: "meter_electricity/battery"
    value_template: "{{ (([(value|float - 3), 1.2]|min / 1.2) * 100) | round(1) }}"
  - platform: mqtt
    name: Gas Meter Total
    unique_id: gas_meter_total
    state_class: total_increasing
    device_class: energy
    state_topic: "meter_gas/total"
    unit_of_measurement: m³
    icon: "mdi:fire"
    value_template: "{{ value | float * 0.01 }}"
  - platform: mqtt
    name: Gas Meter Battery Voltage
    unique_id: gas_meter_battery_voltage
    device_class: voltage
    state_topic: "meter_gas/battery"
    unit_of_measurement: V
    value_template: "{{ value | float }}"
  - platform: mqtt
    name: Gas Meter Battery
    unique_id: gas_meter_battery
    device_class: battery
    unit_of_measurement: "%"
    state_topic: "meter_gas/battery"
    value_template: "{{ (([(value|float - 3), 1.2]|min / 1.2) * 100) | round(1) }}"
  - platform: template
    sensors:
      gas_meter_kwh:
        friendly_name: Gas Meter kWh
        value_template: "{{ states('sensor.gas_meter_total') | float * 0.111868 }}"
        unit_of_measurement: "kWh"
        icon_template: "mdi:fire"
        device_class: gas
